import React,{useState,useEffect} from "react"
import styled from '@emotion/styled';
import Grid from '@mui/material/Grid';
import Button from '@mui/material/Button';
import ListItem from '@mui/material/ListItem';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemText from '@mui/material/ListItemText';
import Head from "next/head"
import Link from "next/link"
import Side from "./side.js"
import { positions } from '@mui/system';
import { css } from '@emotion/react';
import styles from "../../styles/Side.module.css";
import {getSession, useSession } from "next-auth/react";
import useSWR from 'swr'




export default function Main(props){

  const [sides, setSides] = useState();
  const [pro, setPro] = useState([]);
  const [con, setCon] = useState([]);
  const { data: session,status } = useSession();

// const response = useTopics("SideChoosing");
let admin = false;
if(session!= null){
  props.data.forEach((element) =>{
    if (element.user.name == session.user.name){
      admin =true;
    }
  })
}

console.log(session);
const onStorageUpdate = (e) => {
  const { key, newValue } = e;
  if(key ==="Sides"){
    console.log(newValue);
    const pros = []
    const cons = []
  const sides = JSON.parse(newValue);
    sides&&sides.forEach(function(element,index) {
        if (element.side == "Pro") {
          pros.push(element)
        } else {
          cons.push(element)
        }
    })
    setPro(pros);
    setCon(cons);
  }
}



useEffect(() => {
  const pros = []
  const cons = []
  const sides = JSON.parse(localStorage.getItem("Sides"));
  console.log(typeof sides);
  if(sides != null && sides[0] != "" && sides.error == null){
    sides.forEach(function(element,index) {
        if (element.side == "Pro") {

          pros.push(element)
        } else {
          cons.push(element)
        }
    })
    setPro(pros);
    setCon(cons);
  }
  window.addEventListener("storage", onStorageUpdate);
  return () => {
    window.removeEventListener("storage", onStorageUpdate);
  };
}, []);


  function createLi(sides) {
    console.log(localStorage);

    console.log(sides.error);
    const pros = []
    const cons = []
    if(sides != null && sides[0] != "" && sides.error == null){
    sides.forEach(function(element,index) {
        if (element.side == "Pro") {
          // pros.push(<li key={index}>{element.user.name}</li>)
          pros.push(element)
        } else {
          // cons.push(<li key={index} >{element.user.name}</li>)
          cons.push(element)
        }
    })
  }
    localStorage.setItem("Sides",JSON.stringify(sides));
    setPro(pros);
    setCon(cons);

  }
  return(
     <div className={styles.container}>
    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    </Head>
    <Grid container direction="row" sx={{height:1}} spacing={2}>
      <Grid container direction="row" item sx={{width:.5,justifyContent: 'center'}}xs={6}>

              {admin&& <Link href="/admin/ControlPanel" passHref><Button   sx={{
                fontFamily: "Helvetica",
                 fontSize: "1.2em",
                 fontWeight: "bold",
                color: "#fff",
                backgroundColor: "#f5ba13",
                position:"absolute",
                top:"0%",
                left:"0%",
                width: "7%",
                height:"7%",

              }}variant="contained"  size="lg">Admin Panel</Button></Link>}


      <Side elements={pro}  create={createLi} side="Pro"/>
      </Grid>
      <Grid item  container direction="row" sx={{width:.5,justifyContent: 'center' }}xs={6}>
          <Side elements={con} create={createLi} side="Con"/>
        <Link href="/selection/main" passHref><Button   sx={{
          fontFamily: "Helvetica",
           fontSize: "1.2em",
           fontWeight: "bold",
          color: "#fff",
          backgroundColor: "#f5ba13",
          position:"absolute",
          top:"0%",
          right:"0%",
          width: "7%",
          height:"7%",

         }}variant="contained"  size="lg">Choose Topic!</Button></Link>
      </Grid>
    </Grid>

   </div>
  )
}
export async function getServerSideProps(context) {
    const res = await fetch(process.env.NEXTAUTH_URL+"/api/db/Calls/adminHandler", {
      method: "GET",
    })
  const data = await res.json()
  console.log(data);
  const admins = {};

  return { props: {data} }

}
// // {admin&& <Link href="/admin/ControlPanel" passHref><ChangePageRB text="Choose Topic!"></ChangePageRB ></Link>}
// // <Link href="/selection/main" passHref><ChangePageLB text="AdminPanel"></ChangePageLB ></Link>
