import React from "react"
import { Button, Container, Row, Col } from 'react-bootstrap';
import Head from "next/head"
import Side from "./side.js"
import styles from "../../styles/Transcript.module.css";
export default function Transcript(){
  return(
     <div className={styles.container}>
    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link
     rel="stylesheet"
     href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
     integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"
     crossorigin="anonymous"
    />
    </Head>

  <Container fluid>
   <Row>
   <Col lg={2}>
     <Side side="Pro"/>
   </Col>

   <Col className={styles.transcriptCol} lg={8}>
      <textarea  className={styles.transcript} rows="4" cols="50"></textarea>

   </Col>

   <Col className={styles.rightlist} lg={2}>
   <Side side="Con"/>
   </Col>
   </Row>


  </Container>
   </div>
  )
}
