import Head from "next/head";
import Image from "next/image";
import { Button, Container, Row, Col } from 'react-bootstrap';
import { useSession, signIn, signOut,getSession, SessionProvider} from "next-auth/react";
import styles from "../styles/Home.module.css";
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import useSWR from 'swr'

const fetcher = (...args) => fetch(...args).then(res => res.json())
function useDebate(id,token) {
  const { data, error } = useSWR(`/api/db/Calls/${id}`, fetcher)

    return {
      data: data,
      isLoading: !error && !data,
      isError: error

    }
}
export default function HomeScreen(props){
  const {data,isLoading,isError} = useDebate("debateHandler");
  console.log(data)
  console.log(process.env.NEXTAUTH_URL+"/choosing/main");
    console.log(process.env.NEXTAUTH_URL.toString()+"/choosing/main");
      console.log(typeof process.env.NEXTAUTH_URL+"/choosing/main");
      // console.log(session);
  return(
    <div className={styles.container}>
<Head>
<title>Create Next App</title>
<meta name="description" content="Generated by create next app" />
<link
 rel="stylesheet"
 href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
 integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"
  crossOrigin="anonymous"
/>
</Head>
    <h2 className={styles.logo}>Debate Club</h2>

      <Box sx={{
        justifyContent:"center",
        position:"relative",
        bottom:"15%",
        right :"10%",
        fontSize:25,
        width:"50%"
      }}>

    <h1 className={styles.TimeandDate}>Next Debate:{data&&data.date}<br></br>{data&&"Topic:"+data.topic_name}  </h1>
    <button className={styles.signin} onClick={() => {
       console.log(process.env.NEXTAUTH_URL)
          console.log(process.env.NEXTAUTH_URL.toString());
      signIn("google",{ callbackUrl: process.env.NEXTAUTH_URL.toString()+"/choosing/main"})} }>Login</button>
     </Box>
</div>
  )

}
